<?php

namespace AndrewAndante\SilverStripe\AsyncPublisher\Extension;

use SilverStripe\Core\ClassInfo;
use SilverStripe\Core\Extension;
use SilverStripe\ORM\DataObject;
use SilverStripe\ORM\FieldType\DBDatetime;
use SilverStripe\Versioned\ChangeSet;
use SilverStripe\Versioned\Versioned;
use Symbiote\QueuedJobs\DataObjects\QueuedJobDescriptor;
use Symbiote\QueuedJobs\Services\QueuedJob;
use Symbiote\QueuedJobs\Services\QueuedJobService;

class AsyncPublisherExtension extends Extension
{

    public function publishSingle()
    {
        $publishJob = new PublishJob($this->owner, Versioned::LIVE, false);
        QueuedJobService::singleton()->queueJob($publishJob);
    }

    public function publishRecursive()
    {
        $publishJob = new PublishJob($this->owner, Versioned::LIVE, true);
        QueuedJobService::singleton()->queueJob($publishJob);
    }

    public function doPublishSingle()
    {
        $owner = $this->owner;
        // get the last published version
        $original = null;
        if ($owner->isPublished()) {
            $original = Versioned::get_by_stage($owner->baseClass(), Versioned::LIVE)
                ->byID($owner->ID);
        }

        // Publish it
        $owner->invokeWithExtensions('onBeforePublish', $original);
        $owner->writeToStage(Versioned::LIVE);
        $owner->invokeWithExtensions('onAfterPublish', $original);
        return true;
    }

    public function doPublishRecursive()
    {
        $now = DBDatetime::now()->Rfc2822();

        return DBDatetime::withFixedNow($now, function () {
            /** @var DataObject|Versioned $owner */
            $owner = $this->owner;

            // get the last published version
            $original = null;
            if ($owner->hasExtension(Versioned::class) && $owner->isPublished()) {
                $original = Versioned::get_by_stage($owner->baseClass(), Versioned::LIVE)
                    ->byID($owner->ID);
            }

            $owner->invokeWithExtensions('onBeforePublishRecursive', $original);

            // Create a new changeset for this item and publish it
            $changeset = ChangeSet::create();
            $changeset->IsInferred = true;
            $changeset->Name = _t(
                __CLASS__ . '.INFERRED_TITLE',
                "Generated by publish of '{title}' at {created}",
                [
                    'title' => $owner->Title,
                    'created' => DBDatetime::now()->Nice()
                ]
            );

            $changeset->write();
            $changeset->addObject($owner);

            $result = $changeset->publish(true);
            if ($result) {
                $owner->invokeWithExtensions('onAfterPublishRecursive', $original);
            }

            return $result;
        });
    }

    public function canPublish($member = null)
    {
        if (QueuedJobDescriptor::get()->filter([
            'Implementation' => PublishJob::class,
            'Signature' => md5(sprintf('%s-%s', $this->owner->ID, ClassInfo::class_name($this->owner))),
            'JobStatus' => [
                QueuedJob::STATUS_NEW,
                QueuedJob::STATUS_INIT,
                QueuedJob::STATUS_RUN,
                QueuedJob::STATUS_WAIT,
            ]
        ])->exists()) {
            return false;
        }

        return;
    }
}
